### ISSUE TITLE
[server] [Login, Project] - 로그인/초대 이메일 디자인(HTML)

### ISSUE THREAD

**Issue by lovelysi0113** [codestates/Reciper-server#111]
### ISSUE
- Group: `server`
- Type: `design`
- Detail: nodemailer로 보내는 이메일 디자인

### TODO
1. [ ] `post /sendEmail` 요청에서 발송되는 이메일 디자인
2. [ ] `post /pojectInvite/:projectURL` 요청에서 발송되는 이메일 디자인
3. [ ] 잘 만들어졌는지 실제 메일로 확인하기
