### ISSUE TITLE
[server] [Bare Minimum] - workspace route initial setup

### ISSUE THREAD

**Issue by lovelysi0113** [codestates/Reciper-server#123]
### ISSUE
- Group: `server`
- Type: `setup`
- Detail: route를 API문서에 따라 초기 설정합니다. 

### TODO
1. [ ] socekt server와 router를 어떻게 설정할 것인지 회의
2. [ ] workspace
    - [ ] kanban (task)
        - [ ] 데이터 조회
        - [ ] 데이터 저장(실시간)
    - [ ] calendar
        - [ ] 데이터 조회
        - [ ] 데이터 저장(실시간) ?
    - [ ] chat
        - [ ] 채팅 조회
        - [ ] 채팅 저장
