### ISSUE TITLE
[server] [Workspace] - kanban board: 소켓통신화 / 마우스최적화

### ISSUE THREAD

**Issue by gatsukichi** [codestates/Reciper-server#136]
### ISSUE
- Group: `server`
- Type: `feature`
- Detail: 칸반보드 소켓통신에 대해서 구현합니다.

이미 초기작업으로 한번 구현해보았던 내용이지만, 그땐 결과만 이벤트로발생시켜서 소켓에게 뿌려주는형식이였습니다.

하지만 이제는 dragging이라는 옵션을 줌으로써, true/ false로 그 블럭이 누군가가잡았는지를 이벤트화해서 노출시켜야합니다.

(그래야 다른사람이 잡지 않게 블락시킬수있습니다)

마우스의경우도 몇몇 시도가있엇지만, 크롬에서 리소스의 부하를 견디지 못하고 멈추곤했다. 이부분에대한 해결이필요한상황

### TODO
1. [x] DB를 구상해놓긴 했지만 어떻게 저장할지에 대한 내용
2. [x] 저장과 내려줌의 모양을 통일할 필요가있다 (백엔드의 역할) 
3. [ ] 실시간통신에 대한 마우스 리소스부하 대응 전략
