### ISSUE TITLE
[server] [Workspace] - get /workspace/:projectURL 요청 로직 작성

### ISSUE THREAD

**Issue by lovelysi0113** [codestates/Reciper-server#150]
### ISSUE
- Group: `server`
- Type: `feature`
- Detail: 프로젝트 정보 + 멤버 정보 조회

### TODO
1. [x] route setup
2. [x] 로직 작성(데이터베이스 조회)
3. [x] 프로젝트 + 멤버 정보 보내기
3. [x] API 문서 보완
