### ISSUE TITLE
[server] [Workspace] - chat 기능: chat message 삭제하기

### ISSUE THREAD

**Issue by lovelysi0113** [codestates/Reciper-server#160]
### ISSUE
- Group: `server`
- Type: `feature`
- Detail: 채팅방에서 특정 메시지 삭제하기

### TODO
1. [x] 특정 메시지 id 받기
2. [x] 데이터베이스에서 삭제하기
3. [x] 어떻게 다른 사람들에게 알려줄지 고민해보기
3. [x] event name - `deleteMessage`
