### ISSUE TITLE
[server] [Profile] - image를 데이터베이스에 저장, 조회

### ISSUE THREAD

**Issue by lovelysi0113** [codestates/Reciper-server#17]
### ISSUE
- Group: `server`
- Type: `feature`
- Detail: image 업로드, 데이터베이스에 저장하기

### TODO
1. [x] image를 어떻게 업로드할 것인지 회의
2. [x] 어떤 방식으로 데이터베이스에 저장할 것인지 회의
3. [x] 어떻게 클라이언트와 image 데이터를 주고받을 것인지 회의
4. [x] 실제로 구현하기(`get /profile`, `post /profile`)
