### ISSUE TITLE
[server] [Deploy] - Login 기능 테스트 + 에러 수정

### ISSUE THREAD

**Issue by lovelysi0113** [codestates/Reciper-server#219]
### ISSUE
- Group: `server`
- Type: `test`
- Detail: Login 기능 테스트 + 에러 수정

### TODO
1. [x] email 보내기 `post /sendEmail`
2. [x] email 인증 로그인 `post /loginEmail`
3. [x] google OAuth 로그인 `post /loginGoogle`
4. [x] github OAuth 로그인 `post /loginGithub`
5. [ ] 새로운 access token 발급 `get /newAccessToken`
5. [ ] 에러 수정 + 코드 보완
