### ISSUE TITLE
[server] [Deploy] - Profile 기능 테스트 + 에러 수정

### ISSUE THREAD

**Issue by lovelysi0113** [codestates/Reciper-server#220]
### ISSUE
- Group: `server`
- Type: `test`
- Detail: Profile 기능 테스트 + 에러 수정

### TODO
1. [x] 프로필 정보 조회 `get /profile`
2. [x] 프로필 정보 저장/수정 `post /profile`
5. [x] 에러 수정 + 코드 보완
