### ISSUE TITLE
[server] [Deploy] - Recruit 기능 테스트 + 에러 수정

### ISSUE THREAD

**Issue by lovelysi0113** [codestates/Reciper-server#221]
### ISSUE
- Group: `server`
- Type: `test`
- Detail: Recruit 기능 테스트 + 에러 수정

### TODO
1. [ ] 팀원모집 게시글 리스트 조회 `get /recruitList/:order/:sort`
2. [ ] 팀원모집 게시글 상세내용 조회`get /recruitBoard/:board_id`
3. [ ] 팀원모집 게시글 검색 `post /filterRecruitList/:order/:sort`
4. [ ] 팀원모집 게시글 등록 `post /recruitBoard`
5. [ ] 팀원모집 게시글 수정 `post /recruitBoard/:board_id`
6. [ ] 팀원모집 게시글 삭제 `delete /recruitBoard/:board_id`
7. [ ] 댓글 등록 `post /recruitBoardComment/:board_id`
8. [ ] 댓글 삭제 `delete /recruitBoardComment/:board_id/:comment_id`
9. [ ] 에러 수정 + 코드 보완
