### ISSUE TITLE
[server] [Deploy] - Project 기능 테스트 + 에러 수정

### ISSUE THREAD

**Issue by lovelysi0113** [codestates/Reciper-server#222]
### ISSUE
- Group: `server`
- Type: `test`
- Detail: Project 기능 테스트 + 에러 수정

### TODO
1. [ ] 프로젝트 리스트 조회 `get /project`
2. [ ] 프로젝트 생성 `post /project`
3. [ ] 프로젝트 조회 `get /project/:projectURL`
4. [ ] 프로젝트 수정 `post /project/:projectURL`
5. [ ] 프로젝트 삭제 `delete /project/:projectURL`
6. [ ] 팀원 초대 `post /projectInvite/:projectURL`
7. [ ] 팀원 초대 응답(프로젝트 참가) `post /projectParticipate`
8. [ ] 에러 수정 + 코드 보완
