### ISSUE TITLE
[server] [Deploy] - Workspace: Chat 기능 테스트 + 에러 수정

### ISSUE THREAD

**Issue by lovelysi0113** [codestates/Reciper-server#223]
### ISSUE
- Group: `server`
- Type: `test`
- Detail: Workspace: Chat 기능 테스트 + 에러 수정

### TODO
1. [ ] 채팅방 목록 조회 `get /workspace/:projectURL/chat`
2. [ ] 채팅방 생성 `post /workspace/:projectURL/chat`
3. [ ] 채팅방 이름 수정 `post /workspace/:projectURL/chat/:room`
4. [ ] 채팅방 삭제 `delete /workspace/:projectURL/chat/:room`
5. [ ] Socket 통신
    - [ ] 체크
6. [ ] 에러 수정 + 코드 보완
