### ISSUE TITLE
[server] [Deploy] - Workspace: Kanban 기능 테스트 + 에러 수정

### ISSUE THREAD

**Issue by lovelysi0113** [codestates/Reciper-server#224]
### ISSUE
- Group: `server`
- Type: `test`
- Detail: Workspace: Kanban 기능 테스트 + 에러 수정

### TODO
1. [ ] part 목록 조회 `get /workspace/:projectURL/kanban`
2. [ ] part 생성 `post /workspace/:projectURL/kanban`
3. [ ] part 이름 수정 `post /workspace/:projectURL/kanban/:part`
4. [ ] part 삭제 `delete /workspace/:projectURL/kanban/:part`
5. [ ] Socket 통신
    - [ ] 체크
6. [ ] 에러 수정 + 코드 보완
