### ISSUE TITLE
[server] [Recruit] - writer 정보 추가

### ISSUE THREAD

**Issue by lovelysi0113** [codestates/Reciper-server#42]
### ISSUE
- Group: `server`
- Type: `feature`
- Detail: 게시글 상세 정보(recruits) 테이블에 writer 정보 추가

### TODO
1. [x] 스키마 디자인 보완
2. [x] Recruit 테이블의 entity 수정
3. [x] 데이터베이스 초기화
4. [x] Recruit 관련 로직 모두 수정
5. [x] 데이터가 잘 보내지는지 테스트
