### ISSUE TITLE
[server] [Database & Modeling] - DummyDater Seeders 만들기 

### ISSUE THREAD

**Issue by gatsukichi** [codestates/Reciper-server#43]
### ISSUE
- Group: `server`
- Type: `feature`
- Detail: 랜덤하게 더미데이터 생성해서 넣어주는 npm 만들기. 한번 실행시 10개씩 또는 1개씩 실행할것

### TODO
1. [ ] 더미데이터 : 리크루트 만들기
2. [ ] 더미데이터 : 댓글 달기 (파라미터로 리크루트 아이디)
3. [ ] 한방에 ? 더미데이터 10개 댓글 랜덤갯수, 랜덤 문장 작성자 랜덤 id(존재하는 아이디중에)
