### ISSUE TITLE
[server] [Recruit] - dummy generator 오타수정/ bug Fix

### ISSUE THREAD

**Issue by gatsukichi** [codestates/Reciper-server#51]
### ISSUE
- Group: `server`
- Type: `bug`,
- Detail: 오타수정및, 버그 픽스

### TODO
1. [x] 오타 확인/수정
2. [x] commentCount/view count 안먹음
3. [x] stack? map of undefined? 더미에는 stack이 연결안돼나 ?
