### ISSUE TITLE
[server] [Login] - github 로그인 관련 연락처 정보 수정

### ISSUE THREAD

**Issue by lovelysi0113** [codestates/Reciper-server#52]
### ISSUE
- Group: `server`
- Type:  `feature`
- Detail: 유저정보 처리하기

### TODO
1. [ ] github으로 로그인할때 email이 없는 유저가 있는 경우가 있기 때문에 이부분을 어떻게 처리해야할지 고민해봐야한다
2. [ ] recruit 게시글에서 email 정보가 필요하기 때문에 전처럼 github.com으로 유저정보를 저장할 수 없기 때문
3. [ ] 일단 advanced로 넣어두고 차차 고민/해결해보는 방향으로 갈 듯 하다
