### ISSUE TITLE
[server] [Login] - 로그인 안한 유저에게 제공되는 체험모드

### ISSUE THREAD

**Issue by lovelysi0113** [codestates/Reciper-server#53]
### ISSUE
- Group: `server`
- Type: `feature`
- Detail: 로그인 안한 유저에게 제공되는 체험모드 고려

### TODO
1. [x] 로그인 안한 유저도 볼 수 있게 몇몇 라우터에 middeware authChecker 제거
     - [x] `get /recruitList`
     - [x] `get /recruitBoard/:board_id`
2. [ ] 체험 모드에 다른 기능도 넣을 수 있는지 고민+회의해보기
