### ISSUE TITLE
[server] [Recruit] - 댓글 데이터에 유저 정보 추가하기

### ISSUE THREAD

**Issue by lovelysi0113** [codestates/Reciper-server#55]
### ISSUE
- Group: `server`
- Type: `feature`
- Detail: 댓글 데이터에 유저 정보 추가하기

### TODO
1. [x] users, recruit_comments 테이블 reration 만들기
2. [x] 댓글 등록할 때 작성자 정보 저장하기
3. [x] response에 댓글 작성자 정보도 함께 보내기
4. [x] client와 테스트하기
