### ISSUE TITLE
[server] [Recruit] - 게시글 데이터에 유저 정보 추가하기

### ISSUE THREAD

**Issue by lovelysi0113** [codestates/Reciper-server#56]
### ISSUE
- Group: `server`
- Type: `feature`
- Detail: 게시글(보드) 데이터에 유저 정보 추가하기

### TODO
1. [x] users, recruits 테이블 reration 수정하기
2. [x] 게시글 등록할 때 작성자 정보 저장하기
3. [x] response에 게시글 작성자 정보도 함께 보내기
4. [x] client와 테스트하기
