### ISSUE TITLE
[server] [Database&Modeling] - project entity 설계

### ISSUE THREAD

**Issue by gatsukichi** [codestates/Reciper-server#65]
### ISSUE
- Group: `server`
- Type: `feature`
- Detail: Project의 Entity를 설계합니다.

### TODO
1. [ ] Users와 ManyToMany의 관계
2. [ ] project에 여러개의 part를 가진다.
3. [ ] socket.io와 직접적 연결이되는 chat을 가진다 (socket.io에 대한 지식이필요)
