### ISSUE TITLE
[server] [Database&Modeling] - Tasks entity 설계

### ISSUE THREAD

**Issue by gatsukichi** [codestates/Reciper-server#69]
### ISSUE
- Group: `server`
- Type: `feature`
- Detail: task의 entity를 설계합니다. 각 task들은 start,end의 날짜를 가지고, 이는 이후 캘린더에서 보여질때 사용됩니다. 댓글과 n:1관계 , taskBox와 1:n관계이고, checkList를 가지며 또한 1:n관계 입니다.

### TODO
1. [ ] 각 column을 설정 (각 속성확인)
2. [ ] tasks_comment와의 1:n연결
3. [ ] check_list와의 1:n연결
4. [ ] taskBox와의 N:1 연결
