### ISSUE TITLE
[server] [Workspace] - 프로젝트 정보, 유저 정보를 확인하는 middleware 구현

### ISSUE THREAD

**Issue by lovelysi0113** [codestates/Reciper-server#70]
### ISSUE
- Group: `server`
- Type: `feature`
- Detail: project 기능 관련 요청을 처리하기 전에 유저정보, 프로젝트정보 확인해야하는 middleware 구현

### TODO
1. [x] 현재 endpoint가 유효한 프로젝트인지 확인
2. [x] 접근하려는 유저가 이 프로젝트의 팀원인지 확인
3. [x] 클라이언트와 테스트 하기
