### ISSUE TITLE
[server] [Database&Modeling] - 스키마 디자인 점검 및 보완

### ISSUE THREAD

**Issue by lovelysi0113** [codestates/Reciper-server#81]
### ISSUE
- Group: `server`
- Type: `document`
- Detail: 구현하는 로직에 맞춰서 스키마 디자인 보완

### TODO
1. [x] login
2. [x] profile
3. [x] recruit - recruits, recruit_comments, stacks
4. [x] project - projects
5. [x] workspace - parts, task_boxes, tasks, checklists, task_comments
6. [x] 추가할 테이블(chat 등)의 entity, 필드 고민
